name: Docker Image CI

on:
  push:
    branches: ['**']
  pull_request:
    branches: ['**']

jobs:

  hello_world:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build & Run hello world
      working-directory: ./hello_world
      run: |
        cd hello_world
        docker build -t hello-world .
        docker run --name hello hello-world 
